### ISSUE TITLE
pip install breaks codc

### ISSUE THREAD

**Issue by yaswant** [ecmwf/pyodc#6] opened 2021-10-22 15:02 UTC
`pip install codc` does not install `codc` libs correctly, e.g., `processed_odc.h` was missing from 
`<python3_install_path>/lib/python3.8/site-packages/codc/`

**Comment by simondsmart** [comment] 2021-11-10 21:20
How peculiar. @dvuckovic - can you have a look and see what has gone wrong.

**Comment by dvuckovic** [comment] 2021-11-11 09:42
This was peculiar, indeed.

First, I could not reproduce the issue locally, at all. The offending header was always included in the source distribution, just like @matthewrmshin reported.

```
$ python setup.py sdist   
running sdist
...
copying codc/processed_odc.h -> pyodc-1.1.1/codc
...
```

However, I was able to replicate it on the *same* platform where the last release was uploaded from (Github CI/CD). The only difference was the version of `setuptools` used: with older version of the package (< 58), the header file is indeed omitted from the dist.

I thnk by being explicit in `MANIFEST.in`, we can include this file in the distribution no matter what version of `setuptools` is used. As far as I can tell, this issue was present since `pyodc` 1.0.2, [the release history archives on PyPI](https://pypi.org/project/pyodc/#history) do not include the header file at all.

The fix was already applied, I will make sure we do a hotfix release soon and let you know.

```diff
diff --git a/MANIFEST.in b/MANIFEST.in
index 067e13a..4359bf9 100644
--- a/MANIFEST.in
+++ b/MANIFEST.in
@@ -1,3 +1,4 @@
 include CHANGELOG.md
 include LICENSE
 include README.md
+include codc/processed_odc.h
```

Stay tuned.

**Comment by matthewrmshin** [comment] 2021-11-11 09:49
@simondsmart and @dvuckovic Many thanks for looking into this.

**Comment by dvuckovic** [comment] 2021-11-11 11:31
Release with the fix has just been published:

```
pip install pyodc==1.1.2
```

**Comment by simondsmart** [comment] 2021-11-11 11:32
Should be fixed now.

**Closed by simondsmart** 2021-11-11 11:32 UTC

**Comment by matthewrmshin** [comment] 2021-11-11 11:39
Many thanks! I can double confirm that the `codc/processed_odc.h` file is in the 1.1.2 tarball. ✔️

**Comment by yaswant** [comment] 2021-11-11 11:43
I confirm this works now.  Thanks!
